import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth/auth.config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * POST /api/reports/brand-story
 * Generate a downloadable Brand Story Report
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { brandId, format = 'txt' } = body;

    if (!brandId) {
      return NextResponse.json(
        { error: 'Brand ID is required' },
        { status: 400 }
      );
    }

    // Get brand profile
    const brandProfile = await prisma.brandProfile.findUnique({
      where: { id: brandId },
      select: { id: true, brandName: true, domain: true },
    });

    if (!brandProfile) {
      return NextResponse.json(
        { error: 'Brand profile not found' },
        { status: 404 }
      );
    }

    // Try to get Brand360 data for more detailed report
    const brand360 = await prisma.brand360Profile.findFirst({
      where: {
        OR: [
          { id: brandId },
          { organizationId: brandId },
          { brandName: brandProfile.brandName }
        ]
      },
    });

    // Get latest perception scan if available
    let latestScan = null;
    let insights: Array<{ title: string; category: string; priority: string }> = [];

    if (brand360) {
      latestScan = await prisma.perceptionScan.findFirst({
        where: { brand360Id: brand360.id },
        orderBy: { createdAt: 'desc' },
      });

      insights = await prisma.perceptionInsight.findMany({
        where: { brand360Id: brand360.id, status: 'open' },
        orderBy: { priority: 'asc' },
        take: 5,
        select: { title: true, category: true, priority: true },
      });
    }

    const brandName = brandProfile.brandName || 'Your Brand';
    const date = new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });

    // Generate report content
    const summary = `VistralAI has analyzed ${brandName}'s presence across major AI platforms. This report summarizes key findings and recommendations for improving AI visibility.`;

    const wins = [
      brand360?.values?.length
        ? `Brand values clearly defined: ${brand360.values.slice(0, 3).join(', ')}`
        : "Brand identity is being tracked across AI platforms.",
      latestScan?.overallScore
        ? `Current AI perception score: ${Math.round(latestScan.overallScore)}%`
        : "AI platform monitoring is active.",
      brand360?.completionScore
        ? `Brand profile ${brand360.completionScore}% complete`
        : "Product catalog integration available.",
    ];

    const challenges = insights.length > 0
      ? insights.map(i => `[${i.priority.toUpperCase()}] ${i.title}`)
      : [
          "Continue monitoring AI platform responses for accuracy.",
          "Ensure brand information is up-to-date across all channels.",
          "Review competitor positioning regularly.",
        ];

    const recommendations = [
      "Keep your Brand 360 profile complete and up-to-date.",
      "Run regular AI perception scans to monitor brand visibility.",
      "Address high-priority insights promptly to maintain brand accuracy.",
      "Update product information whenever changes occur.",
      "Monitor competitor mentions and positioning.",
    ];

    // Generate text report
    const content = `
================================================================================
                           BRAND STORY REPORT
================================================================================

Brand:          ${brandName}
Date:           ${date}
Generated by:   VistralAI Command Center

================================================================================
                           EXECUTIVE SUMMARY
================================================================================

${summary}

================================================================================
                           KEY HIGHLIGHTS
================================================================================

${wins.map((win, i) => `  ${i + 1}. ${win}`).join('\n')}

================================================================================
                           AREAS FOR ATTENTION
================================================================================

${challenges.map((challenge, i) => `  ${i + 1}. ${challenge}`).join('\n')}

================================================================================
                           RECOMMENDATIONS
================================================================================

${recommendations.map((rec, i) => `  ${i + 1}. ${rec}`).join('\n')}

================================================================================
                           BRAND PROFILE SUMMARY
================================================================================

Brand Name:     ${brandName}
Domain:         ${brandProfile.domain || 'Not set'}
Profile Score:  ${brand360?.completionScore || 0}%
Entity Score:   ${brand360?.entityHealthScore || 0}%
${latestScan ? `
Last Scan:      ${latestScan.completedAt?.toLocaleDateString() || latestScan.createdAt.toLocaleDateString()}
Overall Score:  ${latestScan.overallScore ? Math.round(latestScan.overallScore) + '%' : 'N/A'}
Quadrant:       ${latestScan.quadrantPosition || 'N/A'}
` : ''}
================================================================================
                           CONFIDENTIAL & PROPRIETARY
                      Generated by VistralAI Command Center
================================================================================
`.trim();

    // Return as downloadable file
    const filename = `${brandName.replace(/[^a-zA-Z0-9]/g, '_')}_Brand_Report_${new Date().toISOString().split('T')[0]}.txt`;

    return new NextResponse(content, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });

  } catch (error: unknown) {
    console.error('[Brand Story Report API] Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate report',
        message: errorMessage,
      },
      { status: 500 }
    );
  } finally {
    await prisma.$disconnect();
  }
}
